runtime: python39
service: raw-material 

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    static_files:
      path: static/index.html
      upload: static/index.html
    secure: always
